### ISSUE TITLE
Header image

### ISSUE THREAD

**Issue by samirak98** [TimRoith/TimRoith.github.io#2]
Hi Tim,

the version of the FAU logo that appears in your header image is outdated (but nice cat btw 🐈). Please consider updating the logo to the current version and thereby comply to the FAU styleguide. 

Best, 
Samira

**Comment by TimRoith** [comment]
Dear Samira,

this is a good suggestions. However, I would consider the header image a piece of art and as such it is allowed to employ outdated elements.

Nevertheless the image will be changed soon anyways and maybe I can work in some newer stuff then :wink:

Best,
Tim
